/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author Κωστας
 */
public class GameMenu extends javax.swing.JFrame {

    /**
     * Creates new form GameMenu
     */
    public GameMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        playersturn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        x11 = new javax.swing.JPanel();
        x11text = new javax.swing.JLabel();
        x12 = new javax.swing.JPanel();
        x12text = new javax.swing.JLabel();
        x13 = new javax.swing.JPanel();
        x13text = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        x21 = new javax.swing.JPanel();
        x21text = new javax.swing.JLabel();
        x22 = new javax.swing.JPanel();
        x22text = new javax.swing.JLabel();
        x23 = new javax.swing.JPanel();
        x23text = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        x31 = new javax.swing.JPanel();
        x31text = new javax.swing.JLabel();
        x32 = new javax.swing.JPanel();
        x32text = new javax.swing.JLabel();
        x33 = new javax.swing.JPanel();
        x33text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(550, 310));
        setMinimumSize(new java.awt.Dimension(550, 310));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("TIC-TAC-TOE");
        jPanel3.add(jLabel1);

        jPanel2.add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        playersturn.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        playersturn.setText("PLAYER 1");
        jPanel5.add(playersturn);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        x11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        x11.setMaximumSize(new java.awt.Dimension(102, 102));
        x11.setMinimumSize(new java.awt.Dimension(102, 102));
        x11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x11MouseClicked(evt);
            }
        });

        x11text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        javax.swing.GroupLayout x11Layout = new javax.swing.GroupLayout(x11);
        x11.setLayout(x11Layout);
        x11Layout.setHorizontalGroup(
            x11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x11text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x11Layout.setVerticalGroup(
            x11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x11text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(x11);

        x12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x12text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x12text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x12textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x12Layout = new javax.swing.GroupLayout(x12);
        x12.setLayout(x12Layout);
        x12Layout.setHorizontalGroup(
            x12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x12text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x12Layout.setVerticalGroup(
            x12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x12text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(x12);

        x13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x13text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x13text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x13textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x13Layout = new javax.swing.GroupLayout(x13);
        x13.setLayout(x13Layout);
        x13Layout.setHorizontalGroup(
            x13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x13text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x13Layout.setVerticalGroup(
            x13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x13text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(x13);

        jPanel1.add(jPanel4);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        x21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x21text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x21text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x21textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x21Layout = new javax.swing.GroupLayout(x21);
        x21.setLayout(x21Layout);
        x21Layout.setHorizontalGroup(
            x21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x21text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x21Layout.setVerticalGroup(
            x21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x21text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(x21);

        x22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x22text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x22text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x22textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x22Layout = new javax.swing.GroupLayout(x22);
        x22.setLayout(x22Layout);
        x22Layout.setHorizontalGroup(
            x22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x22text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x22Layout.setVerticalGroup(
            x22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x22text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(x22);

        x23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x23text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x23text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x23textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x23Layout = new javax.swing.GroupLayout(x23);
        x23.setLayout(x23Layout);
        x23Layout.setHorizontalGroup(
            x23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x23text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x23Layout.setVerticalGroup(
            x23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x23text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.add(x23);

        jPanel1.add(jPanel8);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        x31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x31text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x31text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x31textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x31Layout = new javax.swing.GroupLayout(x31);
        x31.setLayout(x31Layout);
        x31Layout.setHorizontalGroup(
            x31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x31text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x31Layout.setVerticalGroup(
            x31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x31text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.add(x31);

        x32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x32text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x32text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x32textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x32Layout = new javax.swing.GroupLayout(x32);
        x32.setLayout(x32Layout);
        x32Layout.setHorizontalGroup(
            x32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x32text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x32Layout.setVerticalGroup(
            x32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x32text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.add(x32);

        x33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        x33text.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        x33text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x33textMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout x33Layout = new javax.swing.GroupLayout(x33);
        x33.setLayout(x33Layout);
        x33Layout.setHorizontalGroup(
            x33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, x33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x33text, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        x33Layout.setVerticalGroup(
            x33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x33text, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.add(x33);

        jPanel1.add(jPanel12);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int player=0;
    private void x11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x11MouseClicked
        // TODO add your handling code here:
        player++;
        if(x11text.getText().equals("")){
            if(player%2==0){
                playersturn.setText("PLAYER 1");
                x11text.setText("O");
            }
            else{
                playersturn.setText("PLAYER 2");
                x11text.setText("X");
            }
        }
        //Player 1 wins
        if((x11text.getText().equals("X"))&&(x12text.getText().equals("X"))&&(x13text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x11text.getText().equals("X"))&&(x21text.getText().equals("X"))&&(x31text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x11text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x33text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x11text.getText().equals("O"))&&(x12text.getText().equals("O"))&&(x13text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x11text.getText().equals("O"))&&(x21text.getText().equals("O"))&&(x31text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x11text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x11MouseClicked

    private void x12textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x12textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x12text.getText().equals("")){
            if(player%2==0){
                playersturn.setText("PLAYER 1");
                x12text.setText("O");
            }
            else{
                playersturn.setText("PLAYER 2");
                x12text.setText("X");
            }
        }
        //Player 1 wins
        if((x11text.getText().equals("X"))&&(x12text.getText().equals("X"))&&(x13text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x12text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x32text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x11text.getText().equals("O"))&&(x12text.getText().equals("O"))&&(x13text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x12text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x32text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x12textMouseClicked

    private void x13textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x13textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x13text.getText().equals("")){
            if(player%2==0){
                x13text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x13text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x11text.getText().equals("X"))&&(x12text.getText().equals("X"))&&(x13text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x13text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x31text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x13text.getText().equals("X"))&&(x23text.getText().equals("X"))&&(x33text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x11text.getText().equals("O"))&&(x12text.getText().equals("O"))&&(x13text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x13text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x31text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x13text.getText().equals("O"))&&(x23text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x13textMouseClicked

    private void x22textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x22textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x22text.getText().equals("")){
            if(player%2==0){
                x22text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x22text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x22text.getText().equals("X"))&&(x12text.getText().equals("X"))&&(x32text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x22text.getText().equals("X"))&&(x21text.getText().equals("X"))&&(x23text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x22text.getText().equals("X"))&&(x11text.getText().equals("X"))&&(x33text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x22text.getText().equals("X"))&&(x13text.getText().equals("X"))&&(x31text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x22text.getText().equals("O"))&&(x12text.getText().equals("O"))&&(x32text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x22text.getText().equals("O"))&&(x21text.getText().equals("O"))&&(x23text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x22text.getText().equals("O"))&&(x11text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x22text.getText().equals("O"))&&(x13text.getText().equals("O"))&&(x31text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x22textMouseClicked

    private void x23textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x23textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x23text.getText().equals("")){
            if(player%2==0){
                x23text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x23text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x23text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x21text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x23text.getText().equals("X"))&&(x13text.getText().equals("X"))&&(x33text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x23text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x21text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x23text.getText().equals("O"))&&(x13text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x23textMouseClicked

    private void x31textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x31textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x31text.getText().equals("")){
            if(player%2==0){
                x31text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x31text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x31text.getText().equals("X"))&&(x32text.getText().equals("X"))&&(x33text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x31text.getText().equals("X"))&&(x21text.getText().equals("X"))&&(x11text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x31text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x13text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x31text.getText().equals("O"))&&(x32text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x31text.getText().equals("O"))&&(x21text.getText().equals("O"))&&(x11text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x31text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x13text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x31textMouseClicked

    private void x32textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x32textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x32text.getText().equals("")){
            if(player%2==0){
                x32text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x32text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x32text.getText().equals("X"))&&(x31text.getText().equals("X"))&&(x33text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x32text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x12text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x32text.getText().equals("O"))&&(x31text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x32text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x12text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x32textMouseClicked

    private void x33textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x33textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x33text.getText().equals("")){
            if(player%2==0){
                x33text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x33text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x33text.getText().equals("X"))&&(x32text.getText().equals("X"))&&(x31text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x33text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x11text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x33text.getText().equals("X"))&&(x23text.getText().equals("X"))&&(x13text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x33text.getText().equals("O"))&&(x32text.getText().equals("O"))&&(x31text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x33text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x11text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x33text.getText().equals("O"))&&(x23text.getText().equals("O"))&&(x13text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x33textMouseClicked

    private void x21textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x21textMouseClicked
        // TODO add your handling code here:
        player++;
        if(x21text.getText().equals("")){
            if(player%2==0){
                x21text.setText("O");
                playersturn.setText("PLAYER 1");
            }
            else{
                x21text.setText("X");
                playersturn.setText("PLAYER 2");
            }
        }
        //Player 1 wins
        if((x21text.getText().equals("X"))&&(x22text.getText().equals("X"))&&(x23text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x21text.getText().equals("X"))&&(x11text.getText().equals("X"))&&(x13text.getText().equals("X"))){
            playersturn.setText("PLAYER 1 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        //Player 2 wins
        if((x21text.getText().equals("O"))&&(x22text.getText().equals("O"))&&(x23text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x21text.getText().equals("O"))&&(x11text.getText().equals("O"))&&(x13text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
        if((x13text.getText().equals("O"))&&(x23text.getText().equals("O"))&&(x33text.getText().equals("O"))){
            playersturn.setText("PLAYER 2 WON");
            jPanel4.setVisible(false);
            jPanel8.setVisible(false);
            jPanel12.setVisible(false);
        }
    }//GEN-LAST:event_x21textMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel playersturn;
    private javax.swing.JPanel x11;
    private javax.swing.JLabel x11text;
    private javax.swing.JPanel x12;
    private javax.swing.JLabel x12text;
    private javax.swing.JPanel x13;
    private javax.swing.JLabel x13text;
    private javax.swing.JPanel x21;
    private javax.swing.JLabel x21text;
    private javax.swing.JPanel x22;
    private javax.swing.JLabel x22text;
    private javax.swing.JPanel x23;
    private javax.swing.JLabel x23text;
    private javax.swing.JPanel x31;
    private javax.swing.JLabel x31text;
    private javax.swing.JPanel x32;
    private javax.swing.JLabel x32text;
    private javax.swing.JPanel x33;
    private javax.swing.JLabel x33text;
    // End of variables declaration//GEN-END:variables
}
